# SPDX-License-Identifier: AGPL-3.0-only
# SPDX-FileCopyrightText: 2026 Tesseract Contributors

[package]
name = "tesseract-vql"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0"
rust-version = "1.85"

[dependencies]
tesseract-common = { path = "../tesseract-common" }
tesseract-core = { path = "../tesseract-core" }
tesseract-storage = { path = "../tesseract-storage" }
nom = "7"
nom_locate = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "time"] }

[dev-dependencies]
tempfile = "3"
tesseract-index = { path = "../tesseract-index" }

[[bin]]
name = "vql"
path = "src/repl.rs"
