// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2026 Tesseract Contributors

//! gRPC API layer — Tonic server implementation.
//!
//! All types and the service trait are generated by tonic-build from
//! `proto/tesseract.proto`. This module is only compiled when the
//! `grpc` feature is enabled.

use std::sync::Arc;

use tokio::sync::mpsc;
use tokio_stream::wrappers::ReceiverStream;
use tonic::{Request, Response, Status};

use tesseract_core::types::VectorId;
use tesseract_storage::engine::StorageEngine;
use tesseract_storage::types::WriteMode;
use tesseract_vql::executor::QueryExecutor;

// ---------------------------------------------------------------------------
// Generated proto types
// ---------------------------------------------------------------------------

tonic::include_proto!("tesseract");

use self::tesseract_query_server::{TesseractQuery, TesseractQueryServer};

// ---------------------------------------------------------------------------
// Service
// ---------------------------------------------------------------------------

/// Tonic service implementation for the `TesseractQuery` gRPC service.
///
/// Mirrors the HTTP handlers in [`crate::http`]: query execution via the
/// [`QueryExecutor`], vector insertion via [`StorageEngine`], and a simple
/// liveness health check.
#[derive(Clone)]
pub struct TesseractQueryService {
    pub executor: Arc<QueryExecutor>,
    pub storage: Arc<StorageEngine>,
}

#[tonic::async_trait]
impl TesseractQuery for TesseractQueryService {
    type QueryStream = ReceiverStream<Result<ScoredRecord, Status>>;

    async fn query(&self, request: Request<QueryRequest>) -> Result<Response<Self::QueryStream>, Status> {
        let req = request.into_inner();
        let vql = req.vql;

        let executor = self.executor.clone();

        // We use a small channel to stream results back to the client.
        // Each result is sent individually as it becomes available.
        let (tx, rx) = mpsc::channel(4);

        tokio::spawn(async move {
            match executor.execute(&vql, None).await {
                Ok(result) => {
                    for sr in result.results {
                        let metadata = sr.metadata.map(|m| m.to_string()).unwrap_or_default();
                        let record = ScoredRecord { id: sr.id, score: sr.score, metadata };
                        if tx.send(Ok(record)).await.is_err() {
                            // Client has disconnected — stop sending.
                            break;
                        }
                    }
                }
                Err(e) => {
                    let _ = tx.send(Err(Status::invalid_argument(e.to_string()))).await;
                }
            }
        });

        Ok(Response::new(ReceiverStream::new(rx)))
    }

    async fn insert(&self, request: Request<InsertRequest>) -> Result<Response<InsertResponse>, Status> {
        let req = request.into_inner();

        let id = req.id;
        let vector: Vec<f64> = req.vector.into_iter().map(|v| v as f64).collect();
        let metadata = match req.metadata {
            Some(ref json_str) => serde_json::from_str(json_str)
                .map_err(|e| Status::invalid_argument(format!("invalid metadata JSON: {e}")))?,
            None => serde_json::json!({}),
        };

        self.storage
            .insert(VectorId(id), vector, metadata, WriteMode::Durable)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;

        Ok(Response::new(InsertResponse { id }))
    }

    async fn health(&self, _request: Request<HealthRequest>) -> Result<Response<HealthResponse>, Status> {
        Ok(Response::new(HealthResponse { status: "ok".to_string() }))
    }
}

// ---------------------------------------------------------------------------
// Server entry
// ---------------------------------------------------------------------------

/// Start the gRPC server, binding to `addr` and serving the
/// `TesseractQueryService`.
pub async fn serve_grpc(
    addr: &str,
    executor: Arc<QueryExecutor>,
    storage: Arc<StorageEngine>,
) -> Result<(), Box<dyn std::error::Error>> {
    let service = TesseractQueryService { executor, storage };
    let socket_addr: std::net::SocketAddr = addr.parse()?;

    tonic::transport::Server::builder().add_service(TesseractQueryServer::new(service)).serve(socket_addr).await?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;
    use tesseract_core::embedding::NoopEmbeddingService;
    use tesseract_core::episodic::EpisodicMemory;
    use tesseract_storage::engine::StorageEngine;
    use tesseract_storage::types::*;
    use tesseract_vql::executor::QueryExecutor;
    use tesseract_vql::planner::PlannerConfig;

    async fn test_storage_and_executor() -> (Arc<StorageEngine>, Arc<QueryExecutor>) {
        let dir = tempfile::tempdir().unwrap();
        let config = StorageConfig {
            wal: WalConfig { wal_dir: dir.path().join("wal"), ..Default::default() },
            hot: HotStoreConfig { max_records: 1000 },
            cold: ColdStoreConfig { data_dir: dir.path().join("cold"), ..Default::default() },
            cache: PageCacheConfig { capacity: 100 },
            skeleton: SkeletonConfig { wake_threshold: 0.5 },
            lifecycle: LifecycleConfig {
                promote_interval_secs: 3600,
                demote_interval_secs: 3600,
                hot_max_records: 1000,
                cold_min_access: 5,
            },
            index: IndexConfig { enabled: true, dim: 4, hnsw: Default::default(), path: dir.path().join("index.hnsw") },
            topological: Default::default(),
            merkle: Default::default(),
            shutdown: ShutdownConfig::default(),
        };
        let storage = Arc::new(StorageEngine::open(config).await.unwrap());
        let embedder = Arc::new(NoopEmbeddingService) as Arc<dyn tesseract_core::embedding::EmbeddingService>;
        let episodic = Arc::new(EpisodicMemory::new());
        let executor = Arc::new(QueryExecutor::new(storage.clone(), embedder, episodic, PlannerConfig::default()));
        (storage, executor)
    }

    #[tokio::test]
    async fn test_health_rpc() {
        let (storage, executor) = test_storage_and_executor().await;
        let service = TesseractQueryService { executor, storage };

        let request = Request::new(HealthRequest {});
        let response = service.health(request).await.unwrap();
        let health = response.into_inner();

        assert_eq!(health.status, "ok");
    }

    #[tokio::test]
    async fn test_insert_rpc() {
        let (storage, executor) = test_storage_and_executor().await;
        let service = TesseractQueryService { executor: executor.clone(), storage: storage.clone() };

        let request = Request::new(InsertRequest {
            id: 42,
            vector: vec![0.1, 0.2, 0.3, 0.4],
            metadata: Some(r#"{"label":"test"}"#.to_string()),
        });
        let response = service.insert(request).await.unwrap();
        let insert_resp = response.into_inner();

        assert_eq!(insert_resp.id, 42);
    }

    #[tokio::test]
    async fn test_insert_rpc_invalid_metadata() {
        let (storage, executor) = test_storage_and_executor().await;
        let service = TesseractQueryService { executor, storage };

        let request = Request::new(InsertRequest {
            id: 1,
            vector: vec![0.1, 0.2, 0.3, 0.4],
            metadata: Some("not valid json".to_string()),
        });
        let result = service.insert(request).await;

        assert!(result.is_err());
        assert_eq!(result.unwrap_err().code(), tonic::Code::InvalidArgument);
    }
}
