// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2026 Tesseract Contributors

//! gRPC API layer — Tonic server implementation.
//!
//! All types and the service trait are generated by tonic-build from
//! `proto/tesseract.proto`. This module is only compiled when the
//! `grpc` feature is enabled.

use std::sync::Arc;

use axum::http;
use tokio::sync::mpsc;
use tokio_stream::wrappers::ReceiverStream;
use tonic::{Request, Response, Status};

use tesseract_core::types::VectorId;
use tesseract_storage::engine::StorageEngine;
use tesseract_storage::types::WriteMode;
use tesseract_vql::executor::QueryExecutor;

use crate::auth::{AuthError, AuthProvider};

/// Build an `http::HeaderMap` from tonic metadata for auth checking.
fn metadata_to_headers(metadata: &tonic::metadata::MetadataMap) -> http::HeaderMap {
    let mut headers = http::HeaderMap::new();
    for kv in metadata.iter() {
        use tonic::metadata::KeyAndValueRef;
        match kv {
            KeyAndValueRef::Ascii(name, value) => {
                if let Ok(header_name) = http::header::HeaderName::from_bytes(name.as_str().as_bytes()) {
                    if let Ok(val_str) = value.to_str() {
                        if let Ok(header_value) = http::header::HeaderValue::from_str(val_str) {
                            headers.insert(header_name, header_value);
                        }
                    }
                }
            }
            KeyAndValueRef::Binary(name, _) => {
                // Skip binary metadata keys — auth only uses ASCII headers.
                let _ = name;
            }
        }
    }
    headers
}

// ---------------------------------------------------------------------------
// Generated proto types
// ---------------------------------------------------------------------------

tonic::include_proto!("tesseract");

use self::tesseract_query_server::{TesseractQuery, TesseractQueryServer};

// ---------------------------------------------------------------------------
// Service
// ---------------------------------------------------------------------------

/// Tonic service implementation for the `TesseractQuery` gRPC service.
///
/// Mirrors the HTTP handlers in [`crate::http`]: query execution via the
/// [`QueryExecutor`], vector insertion via [`StorageEngine`], and a simple
/// liveness health check.
#[derive(Clone)]
pub struct TesseractQueryService {
    pub executor: Arc<QueryExecutor>,
    pub storage: Arc<StorageEngine>,
    pub auth: Option<Arc<Box<dyn AuthProvider>>>,
}

impl TesseractQueryService {
    /// Check authentication for a gRPC request.
    ///
    /// Returns `Ok(())` if auth is disabled or passes, `Err(Status)` otherwise.
    fn check_auth(&self, metadata: &tonic::metadata::MetadataMap) -> Result<(), Status> {
        if let Some(ref auth) = self.auth {
            let headers = metadata_to_headers(metadata);
            auth.authenticate(&headers).map(|_| ()).map_err(|e| match e {
                AuthError::MissingCredentials => Status::unauthenticated("missing credentials"),
                AuthError::InvalidCredentials(msg) => Status::unauthenticated(msg),
                AuthError::ExpiredToken => Status::unauthenticated("token expired"),
            })
        } else {
            Ok(())
        }
    }
}

#[tonic::async_trait]
impl TesseractQuery for TesseractQueryService {
    type QueryStream = ReceiverStream<Result<ScoredRecord, Status>>;

    async fn query(&self, request: Request<QueryRequest>) -> Result<Response<Self::QueryStream>, Status> {
        self.check_auth(request.metadata())?;

        let req = request.into_inner();
        let vql = req.vql;

        let executor = self.executor.clone();

        // We use a small channel to stream results back to the client.
        // Each result is sent individually as it becomes available.
        let (tx, rx) = mpsc::channel(4);

        tokio::spawn(async move {
            match executor.execute(&vql, None).await {
                Ok(result) => {
                    for sr in result.results {
                        let metadata = sr.metadata.map(|m| m.to_string()).unwrap_or_default();
                        let record = ScoredRecord { id: sr.id, score: sr.score, metadata };
                        if tx.send(Ok(record)).await.is_err() {
                            // Client has disconnected — stop sending.
                            break;
                        }
                    }
                }
                Err(e) => {
                    let _ = tx.send(Err(Status::invalid_argument(e.to_string()))).await;
                }
            }
        });

        Ok(Response::new(ReceiverStream::new(rx)))
    }

    async fn insert(&self, request: Request<InsertRequest>) -> Result<Response<InsertResponse>, Status> {
        self.check_auth(request.metadata())?;

        let req = request.into_inner();

        let id = req.id;
        let vector: Vec<f64> = req.vector.into_iter().map(|v| v as f64).collect();
        let metadata = match req.metadata {
            Some(ref json_str) => serde_json::from_str(json_str)
                .map_err(|e| Status::invalid_argument(format!("invalid metadata JSON: {e}")))?,
            None => serde_json::json!({}),
        };

        self.storage
            .insert(VectorId(id), vector, metadata, WriteMode::Durable)
            .await
            .map_err(|e| Status::internal(e.to_string()))?;

        Ok(Response::new(InsertResponse { id }))
    }

    async fn health(&self, _request: Request<HealthRequest>) -> Result<Response<HealthResponse>, Status> {
        // Health endpoint is exempt from auth
        Ok(Response::new(HealthResponse { status: "ok".to_string() }))
    }
}

// ---------------------------------------------------------------------------
// Server entry
// ---------------------------------------------------------------------------

/// Start the gRPC server, binding to `addr` and serving the
/// `TesseractQueryService`.
pub async fn serve_grpc(
    addr: &str,
    executor: Arc<QueryExecutor>,
    storage: Arc<StorageEngine>,
    auth: Option<Arc<Box<dyn AuthProvider>>>,
) -> Result<(), Box<dyn std::error::Error>> {
    let service = TesseractQueryService { executor, storage, auth };
    let socket_addr: std::net::SocketAddr = addr.parse()?;

    tonic::transport::Server::builder().add_service(TesseractQueryServer::new(service)).serve(socket_addr).await?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::auth::Claims;
    use std::collections::HashMap;
    use std::sync::Arc;
    use tesseract_core::embedding::NoopEmbeddingService;
    use tesseract_core::episodic::EpisodicMemory;
    use tesseract_storage::engine::StorageEngine;
    use tesseract_storage::types::*;
    use tesseract_vql::executor::QueryExecutor;
    use tesseract_vql::planner::PlannerConfig;

    fn make_api_key_auth() -> Option<Arc<Box<dyn AuthProvider>>> {
        let mut keys = HashMap::new();
        keys.insert("sk-valid".to_string(), Claims { sub: "test".to_string(), role: "admin".to_string() });
        Some(Arc::new(Box::new(crate::auth::ApiKeyAuth::new(keys))))
    }

    async fn test_storage_and_executor() -> (Arc<StorageEngine>, Arc<QueryExecutor>) {
        let dir = tempfile::tempdir().unwrap();
        let config = StorageConfig {
            wal: WalConfig { wal_dir: dir.path().join("wal"), ..Default::default() },
            hot: HotStoreConfig { max_records: 1000 },
            cold: ColdStoreConfig { data_dir: dir.path().join("cold"), ..Default::default() },
            cache: PageCacheConfig { capacity: 100 },
            skeleton: SkeletonConfig { wake_threshold: 0.5 },
            lifecycle: LifecycleConfig {
                promote_interval_secs: 3600,
                demote_interval_secs: 3600,
                hot_max_records: 1000,
                cold_min_access: 5,
            },
            index: IndexConfig { enabled: true, dim: 4, hnsw: Default::default(), path: dir.path().join("index.hnsw") },
            topological: Default::default(),
            merkle: Default::default(),
            shutdown: ShutdownConfig::default(),
        };
        let storage = Arc::new(StorageEngine::open(config).await.unwrap());
        let embedder = Arc::new(NoopEmbeddingService) as Arc<dyn tesseract_core::embedding::EmbeddingService>;
        let episodic = Arc::new(EpisodicMemory::new());
        let executor = Arc::new(QueryExecutor::new(storage.clone(), embedder, episodic, PlannerConfig::default(), std::time::Duration::from_secs(30)));
        (storage, executor)
    }

    #[tokio::test]
    async fn test_health_rpc() {
        let (storage, executor) = test_storage_and_executor().await;
        let service = TesseractQueryService { executor, storage, auth: None };

        let request = Request::new(HealthRequest {});
        let response = service.health(request).await.unwrap();
        let health = response.into_inner();

        assert_eq!(health.status, "ok");
    }

    #[tokio::test]
    async fn test_insert_rpc() {
        let (storage, executor) = test_storage_and_executor().await;
        let service = TesseractQueryService { executor: executor.clone(), storage: storage.clone(), auth: None };

        let request = Request::new(InsertRequest {
            id: 42,
            vector: vec![0.1, 0.2, 0.3, 0.4],
            metadata: Some(r#"{"label":"test"}"#.to_string()),
        });
        let response = service.insert(request).await.unwrap();
        let insert_resp = response.into_inner();

        assert_eq!(insert_resp.id, 42);
    }

    #[tokio::test]
    async fn test_insert_rpc_invalid_metadata() {
        let (storage, executor) = test_storage_and_executor().await;
        let service = TesseractQueryService { executor, storage, auth: None };

        let request = Request::new(InsertRequest {
            id: 1,
            vector: vec![0.1, 0.2, 0.3, 0.4],
            metadata: Some("not valid json".to_string()),
        });
        let result = service.insert(request).await;

        assert!(result.is_err());
        assert_eq!(result.unwrap_err().code(), tonic::Code::InvalidArgument);
    }

    // -----------------------------------------------------------------------
    // gRPC auth tests
    // -----------------------------------------------------------------------

    #[tokio::test]
    async fn test_auth_query_with_valid_key_succeeds() {
        let (storage, executor) = test_storage_and_executor().await;
        let service = TesseractQueryService { executor, storage, auth: make_api_key_auth() };

        let mut request = Request::new(QueryRequest { vql: "FIND SIMILARITY(emb, VECTOR(0.1, 0.2, 0.3, 0.4)) LIMIT 5".into() });
        request.metadata_mut().insert("x-api-key", tonic::metadata::MetadataValue::from_static("sk-valid"));

        let result = service.query(request).await;
        assert!(result.is_ok(), "query with valid API key should succeed");
    }

    #[tokio::test]
    async fn test_auth_query_without_key_returns_unauthenticated() {
        let (storage, executor) = test_storage_and_executor().await;
        let service = TesseractQueryService { executor, storage, auth: make_api_key_auth() };

        let request = Request::new(QueryRequest { vql: "FIND SIMILARITY(emb, VECTOR(0.1, 0.2, 0.3, 0.4)) LIMIT 5".into() });

        let err = service.query(request).await.unwrap_err();
        assert_eq!(err.code(), tonic::Code::Unauthenticated);
        assert!(err.message().contains("missing credentials"));
    }

    #[tokio::test]
    async fn test_auth_query_with_invalid_key_returns_unauthenticated() {
        let (storage, executor) = test_storage_and_executor().await;
        let service = TesseractQueryService { executor, storage, auth: make_api_key_auth() };

        let mut request = Request::new(QueryRequest { vql: "FIND SIMILARITY(emb, VECTOR(0.1, 0.2, 0.3, 0.4)) LIMIT 5".into() });
        request.metadata_mut().insert("x-api-key", tonic::metadata::MetadataValue::from_static("sk-wrong"));

        let err = service.query(request).await.unwrap_err();
        assert_eq!(err.code(), tonic::Code::Unauthenticated);
    }

    #[tokio::test]
    async fn test_auth_insert_with_valid_key_succeeds() {
        let (storage, executor) = test_storage_and_executor().await;
        let service = TesseractQueryService { executor, storage, auth: make_api_key_auth() };

        let mut request = Request::new(InsertRequest {
            id: 999,
            vector: vec![0.1, 0.2, 0.3, 0.4],
            metadata: None,
        });
        request.metadata_mut().insert("x-api-key", tonic::metadata::MetadataValue::from_static("sk-valid"));

        let result = service.insert(request).await;
        assert!(result.is_ok(), "insert with valid API key should succeed");
    }

    #[tokio::test]
    async fn test_auth_insert_without_key_returns_unauthenticated() {
        let (storage, executor) = test_storage_and_executor().await;
        let service = TesseractQueryService { executor, storage, auth: make_api_key_auth() };

        let request = Request::new(InsertRequest {
            id: 998,
            vector: vec![0.1, 0.2, 0.3, 0.4],
            metadata: None,
        });

        let err = service.insert(request).await.unwrap_err();
        assert_eq!(err.code(), tonic::Code::Unauthenticated);
    }

    #[tokio::test]
    async fn test_auth_health_exempt_from_auth() {
        let (storage, executor) = test_storage_and_executor().await;
        let service = TesseractQueryService { executor, storage, auth: make_api_key_auth() };

        // Health endpoint must succeed without any auth headers.
        let request = Request::new(HealthRequest {});
        let result = service.health(request).await;
        assert!(result.is_ok(), "health endpoint should be exempt from auth");
        assert_eq!(result.unwrap().into_inner().status, "ok");
    }

    #[tokio::test]
    async fn test_auth_disabled_in_none_mode() {
        let (storage, executor) = test_storage_and_executor().await;
        // auth: None means auth is disabled
        let service = TesseractQueryService { executor, storage, auth: None };

        let request = Request::new(QueryRequest { vql: "FIND SIMILARITY(emb, VECTOR(0.1, 0.2, 0.3, 0.4)) LIMIT 5".into() });
        let result = service.query(request).await;
        assert!(result.is_ok(), "query should work without auth when auth is disabled");
    }
}
